name: langchain
repository: https://github.com/davidmigloz/langchain_dart

packages:
  - examples/*
  - packages/*
  - packages/**/example

command:
  version:
    linkToCommits: true
    workspaceChangelog: true
    releaseUrl: true
    branch: main
    changelogs:
      - path: CHANGELOG.md
        description: "📣 Check out the [releases page](https://github.com/davidmigloz/langchain_dart/releases) or the [#announcements](https://discord.com/channels/1123158322812555295/1123250594644242534) channel on the [LangChain.dart Discord](https://discord.gg/x4qbhqecVR) server for more details."
        packageFilters:
          no-private: true
  bootstrap:
    usePubspecOverrides: true
    environment:
      sdk: ">=3.4.0 <4.0.0"
      flutter: ">=3.22.0"
    dependencies:
      async: ^2.12.0
      beautiful_soup_dart: ^0.3.0
      characters: ^1.4.0
      chrome_extension: ^0.4.0
      collection: ^1.19.0
      cross_file: ^0.3.4+2
      crypto: ^3.0.6
      csv: ^6.0.0
      equatable: ^2.0.7
      firebase_app_check: ^0.3.2
      firebase_auth: ^5.5.0
      firebase_core: ^3.12.0
      firebase_vertexai: ^1.4.0
      flat_buffers: ^23.5.26
      flutter_bloc: ^9.0.0
      flutter_markdown: ^0.7.6
      freezed_annotation: ^2.4.4
      gcloud: ^0.8.18
      glob: ^2.1.3
      google_generative_ai: ^0.4.6
      googleapis: ^13.2.0
      googleapis_auth: ^1.6.0
      http: ^1.3.0
      json_annotation: ^4.9.0
      json_path: ^0.7.5
      langchain_tiktoken: ^1.0.1
      logging: ^1.3.0
      math_expressions: ^2.7.0
      meta: ^1.16.0
      objectbox: ^4.1.0
      path: ^1.9.1
      pinecone: ^0.7.2
      rxdart: ">=0.27.7 <0.29.0"
      shared_preferences: ^2.5.0
      shelf: ^1.4.2
      shelf_router: ^1.1.4
      supabase: ^2.6.3
      uuid: ^4.5.1
      web_socket_channel: ^3.0.2
    dev_dependencies:
      build_runner: ^2.4.15
      freezed: ^2.5.8
      json_serializable: ^6.9.4
      objectbox_generator: ^4.1.0
      openapi_spec:
        git:
          url: https://github.com/davidmigloz/openapi_spec.git
          ref: c99a29b7eaad2d25e7ceb90be56e6a9a41066322
      test: ^1.25.15

scripts:
  lint:
    description: Run all static analysis checks
    run: melos run format && melos run analyze

  lint:diff:
    description: Run all static analysis checks failing fast
    run: melos run format:diff && melos run analyze:diff

  format:
    description: Format Dart files
    run: melos exec -- "dart fix --apply"

  format:diff:
    description: Format Flutter files
    run: melos exec --fail-fast -- "dart format --set-exit-if-changed ."
    packageFilters:
      diff: origin/main...HEAD

  analyze:
    description: Run Flutter static analyzer
    run: melos exec -- "flutter analyze ."

  analyze:diff:
    description: Run Flutter static analyzer
    run: melos exec -- "flutter analyze ."
    packageFilters:
      diff: origin/main...HEAD

  test:
    run: melos run test:dart --no-select && melos run test:flutter --no-select
    description: Run all Dart & Flutter tests in this project.

  test:dart:
    run: melos exec -c 1 --fail-fast -- "dart test test"
    description: Run Dart tests for a specific package in this project.
    packageFilters:
      flutter: false
      dirExists: test

  test:flutter:
    run: melos exec -c 1 --fail-fast -- "flutter test test"
    description: Run Flutter tests for a specific package in this project.
    packageFilters:
      flutter: true
      dirExists: test

  test:diff:
    exec: dart test test
    description: Run all Dart tests for changed packages in this project.
    packageFilters:
      diff: origin/main...HEAD
      flutter: false
      dirExists: test

  dep-outdated:
    description: Checks which dependencies have newer versions available.
    run: melos exec -c 1 -- "flutter pub outdated"

  dep-upgrade:
    description: Automatically upgrades package dependencies to the latest versions.
    run: melos exec -c 1 -- "flutter pub upgrade --major-versions"

  fix:
    description: Run Dart/Flutter automated fixes
    run: melos exec -c 1 -- "dart fix --apply"

  codegen:
    description: Run code generation using build_runner
    run: melos exec -c 1 -- "flutter pub run build_runner build --delete-conflicting-outputs && dart format --fix ."
    packageFilters:
      dependsOn: "build_runner"
