name: langchain
repository: https://github.com/davidmigloz/langchain_dart

packages:
  - examples/*
  - packages/*

command:
  version:
    linkToCommits: true
    workspaceChangelog: true
    releaseUrl: true
    branch: main
    changelogs:
      - path: CHANGELOG.md
        description: |
          Check out the #announcements channel in the [LangChain.dart Discord](https://discord.gg/x4qbhqecVR) 
          server for more details about each release.
        packageFilters:
          no-private: true
  bootstrap:
    usePubspecOverrides: true
    environment:
      sdk: ">=3.0.0 <4.0.0"
      flutter: ">=3.19.0"
    dependencies:
      async: ^2.11.0
      beautiful_soup_dart: ^0.3.0
      characters: ^1.3.0
      collection: '>=1.17.0 <1.19.0'
      cross_file: ^0.3.3+4
      crypto: ^3.0.3
      csv: ^5.1.0
      equatable: ^2.0.5
      fetch_client: ^1.0.2
      flutter_bloc: ^8.1.3
      flutter_markdown: ^0.6.17
      freezed_annotation: ^2.4.1
      gcloud: ^0.8.12
      googleapis: ^12.0.0
      googleapis_auth: ^1.4.1
      http: ^1.1.0
      js: ^0.6.7
      json_annotation: ^4.8.1
      json_path: ^0.7.0
      langchain_core: ^0.0.1-dev.2
      langchain_tiktoken: ^1.0.1
      math_expressions: ^2.4.0
      meta: ^1.9.1
      pinecone: ^0.7.2
      shared_preferences: ^2.2.0
      shelf: ^1.4.1
      shelf_router: ^1.1.4
      supabase: ^2.0.6
      uuid: ^4.0.0
    dev_dependencies:
      build_runner: ^2.4.8
      freezed: ^2.4.7
      json_serializable: ^6.7.1
      openapi_spec:
        git:
          url: https://github.com/davidmigloz/openapi_spec.git
          ref: e14c0adaac69e9482e9b57f68fc7964032cdd44c
      test: ^1.25.2

scripts:
  lint:
    description: Run all static analysis checks
    run: melos run format && melos run analyze

  lint:diff:
    description: Run all static analysis checks failing fast
    run: melos run format:diff && melos run analyze:diff

  format:
    description: Format Dart files
    run: melos exec -- "dart format --fix ."

  format:diff:
    description: Format Flutter files
    run: melos exec --fail-fast -- "dart format --fix --set-exit-if-changed ."
    packageFilters:
      diff: origin/main...HEAD

  analyze:
    description: Run Flutter static analyzer
    run: melos exec -- "flutter analyze ."

  analyze:diff:
    description: Run Flutter static analyzer
    run: melos exec -- "flutter analyze ."
    packageFilters:
      diff: origin/main...HEAD

  test:
    run: melos run test:dart --no-select && melos run test:flutter --no-select
    description: Run all Dart & Flutter tests in this project.

  test:dart:
    run: melos exec -c 1 --fail-fast -- "dart test test"
    description: Run Dart tests for a specific package in this project.
    packageFilters:
      flutter: false
      dirExists: test

  test:flutter:
    run: melos exec -c 1 --fail-fast -- "flutter test test"
    description: Run Flutter tests for a specific package in this project.
    packageFilters:
      flutter: true
      dirExists: test

  test:diff:
    exec: dart test test
    description: Run all Dart tests for changed packages in this project.
    packageFilters:
      diff: origin/main...HEAD
      flutter: false
      dirExists: test

  dep-outdated:
    description: Checks which dependencies have newer versions available.
    run: melos exec -c 1 -- "flutter pub outdated"

  dep-upgrade:
    description: Automatically upgrades package dependencies to the latest versions.
    run: melos exec -c 1 -- "flutter pub upgrade --major-versions"

  fix:
    description: Run Dart/Flutter automated fixes
    run: melos exec -c 1 -- "dart fix --apply"

  codegen:
    description: Run code generation using build_runner
    run: melos exec -c 1 -- "flutter pub run build_runner build --delete-conflicting-outputs && dart format --fix ."
    packageFilters:
      dependsOn: "build_runner"
