name: langchain
repository: https://github.com/davidmigloz/langchain_dart

packages:
  - examples/*
  - packages/*
  - packages/**/example

command:
  version:
    linkToCommits: true
    workspaceChangelog: true
    releaseUrl: true
    branch: main
    changelogs:
      - path: CHANGELOG.md
        description: "📣 Check out the [releases page](https://github.com/davidmigloz/langchain_dart/releases) or the [#announcements](https://discord.com/channels/1123158322812555295/1123250594644242534) channel on the [LangChain.dart Discord](https://discord.gg/x4qbhqecVR) server for more details."
        packageFilters:
          no-private: true
  bootstrap:
    usePubspecOverrides: true
    environment:
      sdk: ">=3.4.0 <4.0.0"
      flutter: ">=3.22.0"
    dependencies:
      async: ^2.11.0
      beautiful_soup_dart: ^0.3.0
      characters: ^1.3.0
      collection: ^1.18.0
      cross_file: ^0.3.4+2
      crypto: ^3.0.3
      csv: ^6.0.0
      equatable: ^2.0.5
      fetch_client: ^1.1.2
      firebase_app_check: ^0.3.0
      firebase_auth: ^5.1.0
      firebase_core: ^3.3.0
      firebase_vertexai: ^0.2.2
      flat_buffers: ^23.5.26
      flutter_bloc: ^8.1.6
      flutter_markdown: ^0.7.3
      freezed_annotation: ^2.4.2
      gcloud: ^0.8.12
      google_generative_ai: 0.4.4
      googleapis: ^12.0.0
      googleapis_auth: ^1.6.0
      http: ^1.2.2
      js: ^0.7.1
      json_annotation: ^4.9.0
      json_path: ^0.7.4
      langchain_tiktoken: ^1.0.1
      math_expressions: ^2.6.0
      meta: ^1.11.0
      objectbox: ^4.0.1
      pinecone: ^0.7.2
      rxdart: ">=0.27.7 <0.29.0"
      shared_preferences: ^2.3.0
      shelf: ^1.4.2
      shelf_router: ^1.1.4
      supabase: ^2.2.7
      uuid: ^4.4.2
    dev_dependencies:
      build_runner: ^2.4.11
      freezed: ^2.5.7
      json_serializable: ^6.8.0
      objectbox_generator: ^4.0.1
      openapi_spec:
        git:
          url: https://github.com/davidmigloz/openapi_spec.git
          ref: 93230a5e346b02789f0f727da8eecea9c7bdf118
      test: ^1.25.8

scripts:
  lint:
    description: Run all static analysis checks
    run: melos run format && melos run analyze

  lint:diff:
    description: Run all static analysis checks failing fast
    run: melos run format:diff && melos run analyze:diff

  format:
    description: Format Dart files
    run: melos exec -- "dart format --fix ."

  format:diff:
    description: Format Flutter files
    run: melos exec --fail-fast -- "dart format --fix --set-exit-if-changed ."
    packageFilters:
      diff: origin/main...HEAD

  analyze:
    description: Run Flutter static analyzer
    run: melos exec -- "flutter analyze ."

  analyze:diff:
    description: Run Flutter static analyzer
    run: melos exec -- "flutter analyze ."
    packageFilters:
      diff: origin/main...HEAD

  test:
    run: melos run test:dart --no-select && melos run test:flutter --no-select
    description: Run all Dart & Flutter tests in this project.

  test:dart:
    run: melos exec -c 1 --fail-fast -- "dart test test"
    description: Run Dart tests for a specific package in this project.
    packageFilters:
      flutter: false
      dirExists: test

  test:flutter:
    run: melos exec -c 1 --fail-fast -- "flutter test test"
    description: Run Flutter tests for a specific package in this project.
    packageFilters:
      flutter: true
      dirExists: test

  test:diff:
    exec: dart test test
    description: Run all Dart tests for changed packages in this project.
    packageFilters:
      diff: origin/main...HEAD
      flutter: false
      dirExists: test

  dep-outdated:
    description: Checks which dependencies have newer versions available.
    run: melos exec -c 1 -- "flutter pub outdated"

  dep-upgrade:
    description: Automatically upgrades package dependencies to the latest versions.
    run: melos exec -c 1 -- "flutter pub upgrade --major-versions"

  fix:
    description: Run Dart/Flutter automated fixes
    run: melos exec -c 1 -- "dart fix --apply"

  codegen:
    description: Run code generation using build_runner
    run: melos exec -c 1 -- "flutter pub run build_runner build --delete-conflicting-outputs && dart format --fix ."
    packageFilters:
      dependsOn: "build_runner"
