// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'doc',
        id: 'get_started/intro',
      },
      items: [
        'get_started/installation',
        'get_started/quickstart',
      ],
    },
    'concepts',
    {
      type: 'category',
      label: 'Tutorials',
      link: {
        type: 'doc',
        id: 'tutorials/index',
      },
      items: [
        'tutorials/llm_chain',
        'tutorials/chatbot',
        'tutorials/retrievers',
        'tutorials/agents',
        'tutorials/rag',
        'tutorials/qa_chat_history',
        'tutorials/sql_qa',
        'tutorials/query_analysis',
        'tutorials/local_rag',
        'tutorials/graph',
        'tutorials/pdf_qa',
        'tutorials/extraction',
        'tutorials/data_generation',
        'tutorials/classification',
        'tutorials/summarization',
      ],
    },
    {
      type: 'category',
      label: 'How To',
      link: {
        type: 'doc',
        id: 'how_to/index',
      },
      items: [
        'how_to/installation',
        'how_to/structured_output',
        'how_to/tool_calling',
        'how_to/streaming',
        'how_to/tools',
        'how_to/debugging',
        'how_to/lcel_cheatsheet',
        'how_to/sequence',
        'how_to/parallel',
        'how_to/binding',
        'how_to/functions',
        'how_to/passthrough',
        'how_to/configure',
        'how_to/message_history',
        'how_to/routing',
        'how_to/dynamic_chain',
        'how_to/inspect',
        'how_to/fallbacks',
        'how_to/migrate_chains',
        'how_to/runnable_runtime_secrets',
        'how_to/few_shot_examples',
        'how_to/few_shot_examples_chat',
        'how_to/prompts_partial',
        'how_to/prompts_composition',
        'how_to/chat_model_caching',
        'how_to/logprobs',
        'how_to/custom_chat_model',
        'how_to/chat_streaming',
        'how_to/chat_token_usage_tracking',
        'how_to/response_metadata',
        'how_to/chat_models_universal_init',
        'how_to/tools_few_shot',
        'how_to/tools_model_specific',
        'how_to/tool_choice',
        'how_to/llm_caching',
        'how_to/custom_llm',
        'how_to/streaming_llm',
        'how_to/llm_token_usage_tracking',
        'how_to/local_llms',
        'how_to/document_loader_csv',
        'how_to/document_loader_directory',
        'how_to/document_loader_html',
        'how_to/document_loader_json',
        'how_to/document_loader_markdown',
        'how_to/document_loader_office_file',
        'how_to/document_loader_pdf',
        'how_to/document_loader_custom',
        'how_to/recursive_text_splitter',
        'how_to/HTML_header_metadata_splitter',
        'how_to/HTML_section_aware_splitter',
        'how_to/character_text_splitter',
        'how_to/code_splitter',
        'how_to/markdown_header_metadata_splitter',
        'how_to/recursive_json_splitter',
        'how_to/semantic-chunker',
        'how_to/split_by_token',
        'how_to/vectorstores',
        'how_to/vectorstore_retriever',
        'how_to/MultiQueryRetriever',
        'how_to/contextual_compression',
        'how_to/custom_retriever',
        'how_to/add_scores_retriever',
        'how_to/ensemble_retriever',
        'how_to/long_context_reorder',
        'how_to/multi_vector',
        'how_to/parent_document_retriever',
        'how_to/self_query',
        'how_to/time_weighted_vectorstore',
        'how_to/hybrid',
        'how_to/agent_executor',
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      link: {
        type: 'doc',
        id: 'integrations/index',
      },
      items: [
        'integrations/anthropic',
        'integrations/anyscale',
        'integrations/firebase_vertex_ai',
        'integrations/gcp_vertex_ai',
        'integrations/googleai',
        'integrations/mistralai',
        'integrations/ollama',
        'integrations/open_router',
        'integrations/openai',
        'integrations/prem',
        'integrations/together_ai',
        {
          type: 'category',
          label: 'Tools',
          link: {
            type: 'doc',
            id: 'integrations/tools/index',
          },
          items: [
            'integrations/tools/tavily_answer',
            'integrations/tools/tavily_search_results',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'LCEL',
      link: {
        type: 'doc',
        id: 'lcel/get_started',
      },
      items: [
        'lcel/runnable_interface',
        {
          type: 'category',
          label: 'Primitives',
          link: {
            type: 'doc',
            id: 'lcel/primitives/index',
          },
          items: [
            'lcel/primitives/sequence',
            'lcel/primitives/map',
            'lcel/primitives/passthrough',
            'lcel/primitives/mapper',
            'lcel/primitives/function',
            'lcel/primitives/binding',
            'lcel/primitives/router',
            'lcel/primitives/retry',
          ],
        },
        {
          type: 'category',
          label: 'Cookbooks',
          items: [
            'lcel/cookbooks/prompt_llm_parser',
            'lcel/cookbooks/multiple_chains',
            'lcel/cookbooks/adding_memory',
            'lcel/cookbooks/retrieval',
            'lcel/cookbooks/tools',
          ],
        },
        'lcel/streaming',
        'lcel/fallbacks',
      ],
    },
  ],
};

export default sidebars;