name: googleai_dart
description: Dart Client for the Google AI API (Gemini Pro, Gemini Pro Vision, embeddings, etc.).
version: 0.0.1-dev.1
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/googleai_dart
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.com

topics:
  - ai
  - nlp
  - llms
  - googleai
  - gemini

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  fetch_client: ^1.0.2
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  json_annotation: ^4.8.1
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  #  openapi_spec: ^0.7.8
  openapi_spec:
    git:
      url: https://github.com/davidmigloz/openapi_spec
      ref: b3c3a5518fee569534587dd9296e50a66e51b358
  test: ^1.24.3
