name: googleai_dart
description: Dart Client for the Google AI API (Gemini Pro, Gemini Pro Vision, embeddings, etc.).
version: 0.1.1
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/googleai_dart
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues?q=label:p:googleai_dart
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.dev

funding:
  - https://github.com/sponsors/davidmigloz

topics:
  - ai
  - nlp
  - llms
  - googleai
  - gemini

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace

dependencies:
  freezed_annotation: ^2.4.4
  http: ^1.4.0
  json_annotation: ^4.9.0
  meta: ^1.16.0

dev_dependencies:
  build_runner: ^2.5.1
  freezed: ^2.5.8
  json_serializable: ^6.9.5
#  openapi_spec: ^0.7.8
  openapi_spec:
    git:
      url: https://github.com/davidmigloz/openapi_spec.git
      ref: c99a29b7eaad2d25e7ceb90be56e6a9a41066322
  test: ^1.25.15
