name: googleai_dart
description: Unofficial Dart client for the Google AI Gemini Developer API and Vertex AI Gemini API with unified interface.
version: 1.0.0
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/googleai_dart
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues?q=label:p:googleai_dart
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.dev

funding:
  - https://github.com/sponsors/davidmigloz

topics:
  - nlp
  - gen-ai
  - llms
  - googleai
  - gemini

environment:
  sdk: ">=3.8.0 <4.0.0"
resolution: workspace

dependencies:
  http: ^1.5.0
  logging: ^1.3.0

dev_dependencies:
  test: ^1.26.2
  mocktail: ^1.0.4
  coverage: ^1.15.0
