name: "🚀 Feature Request"
description: Suggest a new feature or enhancement.
labels: ["t:enhancement"]
body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to file a feature request. Before creating a new
        issue, please make sure to take a few moments to check the [issue tracker](https://github.com/davidmigloz/langchain_dart/issues)
        for existing issues about the feature.

  - type: dropdown
    id: package
    validations:
      required: true
    attributes:
      label: Package
      description: >
        Which package from the LangChain.dart ecosystem is this feature related to?
      options:
        - anthropic_sdk_dart
        - chromadb
        - googleai_dart
        - langchain
        - langchain_amazon
        - langchain_anthropic
        - langchain_chroma
        - langchain_cohere
        - langchain_community
        - langchain_core
        - langchain_firebase
        - langchain_google
        - langchain_huggingface
        - langchain_microsoft
        - langchain_mistralai
        - langchain_ollama
        - langchain_openai
        - langchain_pinecone
        - langchain_supabase
        - langchain_weaviate
        - langchain_wikipedia
        - langchain_wolfram
        - langgraph
        - mistralai_dart
        - ollama_dart
        - openai_dart
        - openai_realtime_dart
        - tavily_dart
        - vertex_ai
        - other

  - type: textarea
    id: feature-request
    validations:
      required: true
    attributes:
      label: Feature Request
      description: >
        A clear and concise description of the feature proposal.  

        **Please be as detailed as possible and include:**  
        - **Detailed Description:** What exactly should this feature do?  
        - **Use Cases:**  How would you or others use this feature? Real-world examples are very helpful.  
        - **Example Code Snippets (if applicable):**  Show what the API could look like or how it might be used in code.  
        - **Related Resources:** Links to relevant GitHub repos, papers, other libraries, or documentation that inspired this feature.  

  - type: textarea
    id: motivation
    validations:
      required: true
    attributes:
      label: Motivation
      description: >
        Please outline the motivation for the proposal.  

        **Focus on the problem this feature solves and its impact:**  
        - **Problem:** What problem does this feature address? Be specific and explain the current pain points.  
        - **Benefits:** What are the positive outcomes of implementing this feature?  
        - **Related Issues/Discussions (if any):** Link to existing GitHub issues, discussions, or external conversations that are relevant.  

  - type: textarea
    id: contribution
    validations:
      required: true
    attributes:
      label: Your contribution
      description: >
        Is there any way that you could help, e.g. by submitting a PR or helping to test the feature?
        You can find more information in our [CONTRIBUTING guide](https://github.com/davidmigloz/langchain_dart/blob/main/CONTRIBUTING.md)
