name: "ðŸ› Bug Report"
description: Submit a bug report to help us improve LangChain.dart.
labels: ["t:bug"]
body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to file a bug report. Before creating a new
        issue, please make sure to take a few moments to check the [issue tracker](https://github.com/davidmigloz/langchain_dart/issues)
        for existing issues about the bug.

  - type: dropdown
    id: package
    validations:
      required: true
    attributes:
      label: Package
      description: >
        Which package from the LangChain.dart ecosystem is this bug related to?
      options:
        - anthropic_sdk_dart
        - chromadb
        - googleai_dart
        - langchain
        - langchain_amazon
        - langchain_anthropic
        - langchain_chroma
        - langchain_cohere
        - langchain_community
        - langchain_core
        - langchain_firebase
        - langchain_google
        - langchain_huggingface
        - langchain_microsoft
        - langchain_mistralai
        - langchain_ollama
        - langchain_openai
        - langchain_pinecone
        - langchain_supabase
        - langchain_weaviate
        - langchain_wikipedia
        - langchain_wolfram
        - langgraph
        - mistralai_dart
        - ollama_dart
        - openai_dart
        - openai_realtime_dart
        - tavily_dart
        - vertex_ai
        - other

  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: Reproduction
      description: |
        Please provide a **minimal, reproducible code sample** that clearly demonstrates the bug.  

        **Include:**  
        - **Minimal Code:** The shortest possible code snippet to trigger the bug.  Focus on isolating the issue.  
        - **Steps to reproduce:**  Number the exact steps needed to run the code and see the bug.  
        - **Error Messages/Stack Traces:** Copy and paste any error messages or full stack traces. Use code blocks for formatting.  
        - **Input Data (if applicable):** If the bug depends on specific input data (e.g., a specific prompt or document), include a minimal example of that data as well.  

      placeholder: |
        Steps to reproduce the behavior:
          1. Run this code:
              ```dart
              // Your minimal code example here
              ```
          2. See this error:
              ```
              // Error message or stack trace here
              ```
          3. ... (Further steps if needed)

  - type: textarea
    id: current-behavior
    validations:
      required: true
    attributes:
      label: Current behavior
      description: Describe what is actually happening when you run the code. Be specific and detailed.

  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you would expect to happen if the bug was not present.

  - type: textarea
    id: contribution
    validations:
      required: true
    attributes:
      label: Your contribution
      description: >
        Is there any way that you could help, e.g. by submitting a PR or helping to test the fix?
        You can find more information in our [CONTRIBUTING guide](https://github.com/davidmigloz/langchain_dart/blob/main/CONTRIBUTING.md)
