name: langchain_amazon
description: Amazon module for LangChain.dart.
version: 0.0.1-dev.1
repository: https://github.com/davidmigloz/langchain_dart/tree/main/packages/langchain_amazon
issue_tracker: https://github.com/davidmigloz/langchain_dart/issues
homepage: https://github.com/davidmigloz/langchain_dart
documentation: https://langchaindart.com
publish_to: none # Remove when the package is ready to be published

topics:
  - ai
  - nlp
  - llms
  - langchain

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  langchain: ^0.4.1
  meta: ^1.9.1

dev_dependencies:
  test: ^1.24.3
