include: package:lints/recommended.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - build/**
    - test/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - prefer_relative_imports
    - avoid_print
