name: exception_transparency_lint
description: Custom lint rules to enforce exception transparency principles in Dart code.
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^6.8.0
  custom_lint_builder: ^0.6.7

dev_dependencies:
  custom_lint: ^0.6.7
  lints: ^4.0.0
  test: ^1.21.0
